### ISSUE TITLE
btcchina 的 AccessKey怎么申请啊？

### ISSUE THREAD

**Issue by YoleYu** [shallwe/btcchina_agent#1]
看了文档，但是不知道AccessKey怎么申请

**Comment by shallwe** [comment]
在

shallwe19

发件人： Yole
发送时间： 2013-12-02 18:02
收件人： shallwe/btcchina_agent
主题： [btcchina_agent] btcchina 的 AccessKey怎么申请啊？ (#1)
看了文档，但是不知道AccessKey怎么申请

**Comment by YoleYu** [comment]
什么都没看到啊~~在哪儿呢~？

**Comment by shallwe** [comment]
登录比特币中国后，在左侧往下拉，拉到下面有一个  API访问 NEW的按钮，点击后，在页面中间会出现API访问密钥，下面有个创建 API 密钥对，点击你就看到了

shallwe19

发件人： Yole
发送时间： 2013-12-02 18:53
收件人： shallwe/btcchina_agent
抄送： Shallwe Zhang
主题： Re: [btcchina_agent] btcchina 的 AccessKey怎么申请啊？ (#1)
什么都没看到啊~~在哪儿呢~？

**Comment by shallwe** [comment]
PS 如果有好的行之有效的算法，透露一下，我目前自己写的这套算法，成效不咋地

shallwe19

发件人： Yole
发送时间： 2013-12-02 18:53
收件人： shallwe/btcchina_agent
抄送： Shallwe Zhang
主题： Re: [btcchina_agent] btcchina 的 AccessKey怎么申请啊？ (#1)
什么都没看到啊~~在哪儿呢~？

**Comment by YoleYu** [comment]
看到了~谢谢~我准备也搞一个程序化的交易，试试还能不能有收益~

**Comment by YoleYu** [comment]
再请教个问题，tccchina的哪个API可以获取一段时间的交易量啊？
